/**
 * BotAI - AI controller for bot players with difficulty levels.
 *
 * Bots move around the arena, use abilities, and try to
 * eliminate other players. Each bot has its own AbilitySystem.
 *
 * Difficulties: 'easy' | 'medium' | 'hard'
 * - Easy: slow movement, rarely uses abilities, mostly wanders
 * - Medium: normal speed, moderate ability usage, balanced AI
 * - Hard: fast movement, aggressive ability usage, smart chasing
 *
 * Behaviors:
 * - Wander: change direction every few seconds
 * - Chase: move toward nearest visible player
 * - Flee: move away when low on options
 * - Use abilities with randomness based on difficulty
 */
class BotAI {
  static DIFFICULTY_PROFILES = {
    easy: {
      speedMultiplier: 0.55,       // Slower movement
      abilityCheckBase: 4,         // Check abilities less often
      abilityCheckRandom: 5,
      jumpCheckBase: 10,           // Jump rarely
      jumpCheckRandom: 10,
      hideChance: 0.1,             // Low hide chance
      forceHideChance: 0.05,       // Very low force hide
      forceUnhideChance: 0.15,
      jumpChance: 0.2,             // Low jump chance
      chaseChance: 0.25,           // Rarely chases
      fleeChance: 0.15,            // Rarely flees
      chaseRange: 8,               // Only chases nearby
      wanderChangeMin: 2,          // Changes direction less often
      wanderChangeMax: 4,
    },
    medium: {
      speedMultiplier: 0.85,
      abilityCheckBase: 1.5,
      abilityCheckRandom: 3,
      jumpCheckBase: 5,
      jumpCheckRandom: 5,
      hideChance: 0.3,
      forceHideChance: 0.15,
      forceUnhideChance: 0.4,
      jumpChance: 0.5,
      chaseChance: 0.5,
      fleeChance: 0.35,
      chaseRange: 15,
      wanderChangeMin: 1,
      wanderChangeMax: 2.5,
    },
    hard: {
      speedMultiplier: 1.15,       // Faster movement
      abilityCheckBase: 0.5,       // Uses abilities aggressively
      abilityCheckRandom: 1.5,
      jumpCheckBase: 2,            // Jumps often
      jumpCheckRandom: 3,
      hideChance: 0.45,            // Frequently hides
      forceHideChance: 0.35,       // Often force hides targets
      forceUnhideChance: 0.6,
      jumpChance: 0.7,             // High jump chance
      chaseChance: 0.75,           // Very aggressive chasing
      fleeChance: 0.5,             // Good at fleeing danger
      chaseRange: 25,              // Chases from far away
      wanderChangeMin: 0.5,        // Quick direction changes
      wanderChangeMax: 1.5,
    },
  };

  constructor(player, arena, difficulty = 'medium') {
    this.player = player;
    this.arena = arena;
    this.abilities = new AbilitySystem();
    this.difficulty = difficulty;
    this.profile = BotAI.DIFFICULTY_PROFILES[difficulty] || BotAI.DIFFICULTY_PROFILES.medium;

    // Movement
    this.facing = player.facing || 'up';
    this.directionTimer = 0;
    this.directionInterval = this.profile.wanderChangeMin +
      Math.random() * (this.profile.wanderChangeMax - this.profile.wanderChangeMin);

    // AI state
    this.state = 'wander'; // 'wander' | 'chase' | 'flee'
    this.targetPlayer = null;
    this.stateTimer = 0;

    // Ability usage timers (random delays so bots don't all act at once)
    this.abilityCheckTimer = this.profile.abilityCheckBase + Math.random() * this.profile.abilityCheckRandom;
    this.jumpCheckTimer = this.profile.jumpCheckBase + Math.random() * this.profile.jumpCheckRandom;

    // Directions for easy iteration
    this.DIRECTIONS = ['up', 'down', 'left', 'right'];
    this.DIR_VECTORS = {
      'up':    { x:  0, z: -1 },
      'down':  { x:  0, z:  1 },
      'left':  { x: -1, z:  0 },
      'right': { x:  1, z:  0 },
    };
  }

  /**
   * Update the bot each frame.
   * @param {number} dt - Delta time in seconds
   * @param {Player[]} allPlayers - All players (including this bot)
   * @param {number} gameTime - Current game time in ms
   * @returns {Object[]} - Array of events generated by this bot
   */
  update(dt, allPlayers, gameTime) {
    if (this.player.state === 'eliminated') return [];

    const events = [];

    // Update ability timers
    const autoEvent = this.abilities.update(dt);
    if (autoEvent && autoEvent.type === 'unhide') {
      this.player.setHidden(false);
      events.push({ type: 'unhide', from: this.player.id });
    }

    // Handle jump animation
    if (this.abilities.isJumping) {
      const others = allPlayers.filter(
        (p) => p.id !== this.player.id && p.state !== 'eliminated'
      );
      const result = this.abilities.updateJump(dt, others);
      if (result) {
        this.player.x = result.x;
        this.player.z = result.z;

        for (const hitPlayer of result.hitPlayers) {
          if (!hitPlayer._botJumpHit) {
            hitPlayer._botJumpHit = true;
            events.push({
              type: 'eliminate',
              target: hitPlayer.id,
              by: this.player.id,
              method: 'jump',
            });
          }
        }

        if (result.done) {
          others.forEach((p) => delete p._botJumpHit);
        }
      }
      return events; // Don't do anything else during jump
    }

    // Don't move or use abilities while hidden (except auto-unhide above)
    if (this.player.state === 'hidden') {
      return events;
    }

    // ─── AI Decision Making ──────────────────────────────

    const visibleEnemies = allPlayers.filter(
      (p) => p.id !== this.player.id &&
             p.state !== 'eliminated' &&
             p.state !== 'hidden'
    );

    const allEnemies = allPlayers.filter(
      (p) => p.id !== this.player.id && p.state !== 'eliminated'
    );

    // State machine
    this.stateTimer -= dt;
    if (this.stateTimer <= 0) {
      this._chooseState(visibleEnemies);
    }

    // ─── Movement ────────────────────────────────────────

    this.directionTimer -= dt;

    if (this.state === 'chase' && this.targetPlayer &&
        this.targetPlayer.state !== 'eliminated') {
      // Move toward target
      this._chaseTarget(dt);
    } else if (this.state === 'flee') {
      // Move away from nearest enemy
      this._fleeFromNearest(dt, visibleEnemies);
    } else {
      // Wander
      if (this.directionTimer <= 0) {
        this._changeDirection();
      }
      this._wander(dt);
    }

    // ─── Ability Usage ──────────────────────────────────

    this.abilityCheckTimer -= dt;
    this.jumpCheckTimer -= dt;

    // Try to use abilities
    if (this.abilityCheckTimer <= 0) {
      this.abilityCheckTimer = this.profile.abilityCheckBase + Math.random() * this.profile.abilityCheckRandom;

      // Hide when an enemy is close (defensive)
      if (visibleEnemies.length > 0) {
        const nearest = this._findNearest(visibleEnemies);
        const dist = this.player.distanceTo(nearest);

        if (dist < 5 && this.abilities.canHide() && Math.random() < this.profile.hideChance) {
          const event = this.abilities.useHide();
          if (event) {
            this.player.setHidden(true);
            events.push({ type: 'hide', from: this.player.id });
          }
        }
      }

      // Force Hide on a random enemy (if available)
      if (this.abilities.canForceHide() && allEnemies.length > 0 && Math.random() < this.profile.forceHideChance) {
        const target = allEnemies[Math.floor(Math.random() * allEnemies.length)];
        const event = this.abilities.confirmForceHide(target.id);
        if (event) {
          events.push({ ...event, from: this.player.id });
        }
      }

      // Force Unhide on a hidden enemy
      if (this.abilities.canForceUnhide()) {
        const hiddenEnemies = allEnemies.filter((p) => p.state === 'hidden');
        if (hiddenEnemies.length > 0 && Math.random() < this.profile.forceUnhideChance) {
          const target = hiddenEnemies[Math.floor(Math.random() * hiddenEnemies.length)];
          const event = this.abilities.confirmForceUnhide(target.id);
          if (event) {
            events.push({ ...event, from: this.player.id });
          }
        }
      }
    }

    // Jump attack
    if (this.jumpCheckTimer <= 0) {
      this.jumpCheckTimer = this.profile.jumpCheckBase + Math.random() * this.profile.jumpCheckRandom;

      if (this.abilities.canJump() && visibleEnemies.length > 0) {
        // Check if any enemy is in a straight line from us
        const nearest = this._findNearest(visibleEnemies);
        const jumpFacing = this._getAlignedDirection(nearest);

        if (jumpFacing && Math.random() < this.profile.jumpChance) {
          this.facing = jumpFacing;
          this.player.setFacing(jumpFacing);
          const event = this.abilities.useJump(
            jumpFacing, this.player.x, this.player.z
          );
          if (event) {
            events.push({ ...event, from: this.player.id });
          }
        }
      }
    }

    return events;
  }

  // ─── State Machine ─────────────────────────────────────

  _chooseState(visibleEnemies) {
    if (visibleEnemies.length === 0) {
      this.state = 'wander';
      this.stateTimer = 2 + Math.random() * 3;
      return;
    }

    const nearest = this._findNearest(visibleEnemies);
    const dist = this.player.distanceTo(nearest);

    if (dist < 4 && Math.random() < this.profile.fleeChance) {
      // Close enemy - might flee
      this.state = 'flee';
      this.stateTimer = 1 + Math.random() * 2;
    } else if (dist < this.profile.chaseRange && Math.random() < this.profile.chaseChance) {
      // Medium range - chase
      this.state = 'chase';
      this.targetPlayer = nearest;
      this.stateTimer = 2 + Math.random() * 3;
    } else {
      this.state = 'wander';
      this.stateTimer = 1.5 + Math.random() * 2;
    }
  }

  // ─── Movement Behaviors ────────────────────────────────

  _wander(dt) {
    const dir = this.DIR_VECTORS[this.facing];
    if (dir) {
      this.player.move(dir.x * this.profile.speedMultiplier, dir.z * this.profile.speedMultiplier, dt, this.arena);
      this.player.setFacing(this.facing);
    }
  }

  _chaseTarget(dt) {
    const dx = this.targetPlayer.x - this.player.x;
    const dz = this.targetPlayer.z - this.player.z;

    // Choose the axis with the bigger difference
    if (Math.abs(dx) > Math.abs(dz)) {
      this.facing = dx > 0 ? 'right' : 'left';
    } else {
      this.facing = dz > 0 ? 'down' : 'up';
    }

    const dir = this.DIR_VECTORS[this.facing];
    this.player.move(dir.x * this.profile.speedMultiplier, dir.z * this.profile.speedMultiplier, dt, this.arena);
    this.player.setFacing(this.facing);
  }

  _fleeFromNearest(dt, enemies) {
    if (enemies.length === 0) {
      this._wander(dt);
      return;
    }

    const nearest = this._findNearest(enemies);
    const dx = this.player.x - nearest.x;
    const dz = this.player.z - nearest.z;

    // Move away
    if (Math.abs(dx) > Math.abs(dz)) {
      this.facing = dx > 0 ? 'right' : 'left';
    } else {
      this.facing = dz > 0 ? 'down' : 'up';
    }

    const dir = this.DIR_VECTORS[this.facing];
    this.player.move(dir.x * this.profile.speedMultiplier, dir.z * this.profile.speedMultiplier, dt, this.arena);
    this.player.setFacing(this.facing);
  }

  _changeDirection() {
    // Pick a new random direction, biased away from walls
    const x = this.player.x;
    const z = this.player.z;
    const margin = Arena.HALF - 3;

    let candidates = [...this.DIRECTIONS];

    // Remove directions that would move us into a wall
    if (x > margin) candidates = candidates.filter((d) => d !== 'right');
    if (x < -margin) candidates = candidates.filter((d) => d !== 'left');
    if (z > margin) candidates = candidates.filter((d) => d !== 'down');
    if (z < -margin) candidates = candidates.filter((d) => d !== 'up');

    if (candidates.length === 0) candidates = [...this.DIRECTIONS];

    this.facing = candidates[Math.floor(Math.random() * candidates.length)];
    this.player.setFacing(this.facing);
    this.directionInterval = this.profile.wanderChangeMin + Math.random() * (this.profile.wanderChangeMax - this.profile.wanderChangeMin);
    this.directionTimer = this.directionInterval;
  }

  // ─── Helpers ───────────────────────────────────────────

  _findNearest(players) {
    let nearest = null;
    let minDist = Infinity;

    for (const p of players) {
      const dist = this.player.distanceTo(p);
      if (dist < minDist) {
        minDist = dist;
        nearest = p;
      }
    }

    return nearest;
  }

  /**
   * Check if a target is roughly aligned on one axis (for jump attack).
   * Returns the facing direction to use, or null if not aligned.
   */
  _getAlignedDirection(target) {
    const dx = target.x - this.player.x;
    const dz = target.z - this.player.z;

    const alignThreshold = 2; // How close to axis they need to be

    if (Math.abs(dx) < alignThreshold && Math.abs(dz) > 2) {
      return dz < 0 ? 'up' : 'down';
    }
    if (Math.abs(dz) < alignThreshold && Math.abs(dx) > 2) {
      return dx > 0 ? 'right' : 'left';
    }

    return null;
  }
}
